# https://prettier.io/docs/en/options.html
---
tabWidth: 4
printWidth: 400 #换行字符串阈值
singleQuote: true #用单引号
semi: true #句末加分号
trailingComma: all #最后一个对象元素加逗号
arrowParens: avoid #(x) => {} 是否要有小括号
proseWrap: preserve #是否要换行
